inherits: ../base.yaml
train:
  run_name: hopper_random
  epochs: 200
  steps_per_epoch: 1000000
  max_ep_len: 1000
env:
  type: mujoco
  id: Hopper-v5
method:
  name: random
  variant: uniform
algo:
  estimator: paper_mc
  normalize_weights: false
  bootstrap_truncated_paths: false
model:
  policy_hidden_sizes: [50]
  value_hidden_sizes: [50]
  init_log_std: -0.5
