inherits: ../base.yaml
train:
  run_name: swimmer_single_path
  epochs: 200
  steps_per_epoch: 100000
  max_ep_len: 1000
env:
  type: mujoco
  id: Swimmer-v5
algo:
  max_kl: 0.01
  gamma: 0.99
  lam: 1.0
  estimator: trpo_paper
  normalize_weights: false
  bootstrap_truncated_paths: false
  vf_lr: 0.001
  vf_iters: 80
  vf_batch_size: 4096
model:
  activation: tanh
  policy_hidden_sizes: [30]
  value_hidden_sizes: [30]
  init_log_std: -0.5
