inherits: ../base.yaml
train:
  run_name: swimmer_random
env:
  type: mujoco
  id: Swimmer-v5
method:
  name: random
  variant: uniform
algo:
  estimator: trpo_paper
  normalize_weights: false
  bootstrap_truncated_paths: false
model:
  policy_hidden_sizes: [30]
  value_hidden_sizes: [30]
  init_log_std: -0.5
