inherits: ../base.yaml
train:
  run_name: walker2d_ppo_clip
  epochs: 200
  steps_per_epoch: 100000
  max_ep_len: 1000
env:
  type: mujoco
  id: Walker2d-v5
method:
  name: ppo
  variant: clip
algo:
  gamma: 0.99
  lam: 0.95
  estimator: gae
  normalize_weights: true
  bootstrap_truncated_paths: true
  ppo_clip_ratio: 0.2
  ppo_update_epochs: 10
  ppo_minibatch_size: 2048
  ppo_eval_batch_size: 4096
  ppo_target_kl: 0.01
  ppo_pi_lr: 0.0003
  ppo_vf_lr: 0.001
  ppo_vf_epochs: 10
  ppo_entropy_coef: 0.0
  ppo_max_grad_norm: 0.5
model:
  activation: tanh
  policy_hidden_sizes: [64, 64]
  value_hidden_sizes: [64, 64]
  init_log_std: -0.5
