inherits: ../base.yaml
train:
  memory_mode: safe
  run_name: breakout_single_path
  epochs: 500
  steps_per_epoch: 100000
  max_ep_len: 10000
env:
  type: atari
  id: ALE/Breakout-v5
algo:
  max_kl: 0.01
  gamma: 0.99
  lam: 1.0
  estimator: paper_mc
  normalize_weights: false
  bootstrap_truncated_paths: false
  vf_lr: 0.0003
  vf_iters: 40
  vf_batch_size: 2048
model:
  activation: relu
  policy_hidden_sizes: []
  value_hidden_sizes: []
  cnn_fc_dim: 20
